# Generated by Django 5.1.4 on 2025-01-17 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPLOAD_VIDEO_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedvideo',
            name='processing_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
